import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { Analytics } from "@vercel/analytics/react"
import "./globals.css";

const jost = Jost({ subsets: ['latin'] });


export const metadata: Metadata = {
  title: 'Website SASS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className}`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
