import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Website SASS",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
  params: {
    locale: "en" | "es" | "pt";
  };
};
export default async function LocaleLayout(props: Props) {
  const { children, params } = props;
  const { locale } = await params;

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body className={`${jost.className}`}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
        <Analytics />
      </body>
    </html>
  );
}
